service: orderservice

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: eu-west-1
  memorySize: 128
  timeout: 15  

custom:    
  defaultStage: dev
  profiles:
    dev: dev
    staging: staging
    production: prod  

functions:
  retrieve:
    handler: src/Handler.retrieve
    description: function for retrieving orders
    events:
      - http:
          path: orders
          method: get
          private: true

package:
  exclude:
    - node_modules/@types/**
    - node_modules/nyc/**
    - node_modules/typescript/**
    - node_modules/mocha/**
    - node_modules/mocha-teamcity-reporter/**
    - node_modules/chai/**
    - node_modules/chai-string/**